name: toolchain.yaml
on:
  push:
    paths:
      - runtime/toolchain/**
  workflow_dispatch:


jobs:
  build-docker:
    runs-on: ubuntu-22.04
    steps:
      # Free up disk space on Github-hosted runner
      - name: Disk usage
        run: df -h
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Disk usage after freeing up space
        run: df -h
      # Actually build the Docker container
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: GHCR Log-in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{github.workspace}}/runtime/toolchain/
          file: ${{github.workspace}}/runtime/toolchain/Dockerfile
          push: true
          tags: ghcr.io/opencompl/Quidditch/toolchain:${{ github.ref_name }}
